services:
  prometheus:
    image: prom/prometheus:latest
    container_name: subs-tracker-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - subs-tracker-network

  grafana:
    image: grafana/grafana:latest
    container_name: subs-tracker-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    networks:
      - subs-tracker-network
    depends_on:
      - prometheus

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter
    container_name: subs-tracker-rabbitmq-exporter
    restart: unless-stopped
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=admin
      - RABBIT_PASSWORD=secret
    networks:
      - subs-tracker-network
    depends_on:
      - rabbitmq

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: subs-tracker-redis-exporter
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis-cache:6379
    networks:
      - subs-tracker-network
    depends_on:
      - redis-cache

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local